version: "3.6"

services:
  shinyproxy:
    image: hnskde/shinyproxy-imongr
    restart: unless-stopped
    container_name: shinyproxy
    environment:
      IMONGR_DB_HOST: ${IMONGR_DB_HOST}
      IMONGR_DB_HOST_VERIFY: ${IMONGR_DB_HOST_VERIFY}
      IMONGR_DB_HOST_QA: ${IMONGR_DB_HOST_QA}
      IMONGR_DB_NAME: ${IMONGR_DB_NAME}
      IMONGR_DB_USER: ${IMONGR_DB_USER}
      IMONGR_DB_PASS: ${IMONGR_DB_PASS}
      IMONGR_ADMINER_URL: ${IMONGR_ADMINER_URL}
      OPENID_CLIENT_ID: ${OPENID_CLIENT_ID}
      OPENID_CLIENT_SECRET: ${OPENID_CLIENT_SECRET}
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_S3_ACCESS_SECRET: ${AWS_S3_ACCESS_SECRET}
      APPLICATION_IMAGE_TAG: ${APPLICATION_IMAGE_TAG}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    networks:
      - mongr-net
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-1
        awslogs-group: shinyproxy-imongr
        awslogs-stream: ${NODE_NAME}
        awslogs-create-group: "true"
networks:
  mongr-net:
    name: mongr-net
