services:
  shinyproxy:
    build: .
    restart: unless-stopped
    container_name: shinyproxyazure
    environment:
      IMONGR_DB_HOST: ${IMONGR_DB_HOST}
      IMONGR_DB_NAME: ${IMONGR_DB_NAME}
      IMONGR_DB_USER: ${IMONGR_DB_USER}
      IMONGR_DB_PASS: ${IMONGR_DB_PASS}
      IMONGR_ADMINER_URL: ${IMONGR_ADMINER_URL}
      OPENID_CLIENT_ID: ${OPENID_CLIENT_ID}
      OPENID_CLIENT_SECRET: ${OPENID_CLIENT_SECRET}
      distribution_id: ${distribution_id}
      APPLICATION_IMAGE_TAG: ${APPLICATION_IMAGE_TAG}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/shinyproxy/:/opt/shinyproxy/logs/
    ports:
      - 8080:8080
    networks:
      - mongr_net
    logging:
      driver: json-file
networks:
  mongr_net:
    name: mongr_net

